### ISSUE TITLE
Connect to remote server origin

### ISSUE THREAD

**Issue by Ejb503** [modelcontextprotocol/specification#113]
I have configured a custom MCP server in PhP, using SSE. Everything works great but there is a check in the endpoint listener for matching origins: 

            this._eventSource.addEventListener("endpoint", (event) => {
                var _a;
                const messageEvent = event;
                try {
                    this._endpoint = new URL(messageEvent.data, this._url);
                    if (this._endpoint.origin !== this._url.origin) {
                        throw new Error(`Endpoint origin does not match connection origin: ${this._endpoint.origin}`);
                    }
                }

The integration works perfectly when I remove this check, however I'm curious as to whether this is a "feature" or a "bug" and what the recommendation is for connecting to a remote origin. 

My plan is to use my server as a remote integration...

**Comment by jspahrsummers** [comment]
This is by design, and specified as required in the spec, as it's a security issue to redirect elsewhere.

What are you trying to do that isn't supported on the same origin?

**Comment by Ejb503** [comment]
Basically trying to use a local client with a remote server (npm run dev to run the client, separate endpoint for the server). 

I plan to opensource the client and enable people to download, adapt, and use the client from any origin.

Obviously therefore requests are localhost ----> remoteOrigin... 

My server is configured as one to many, in that clients authenticate via an API key and the single server can thus 'serve' many different clients, I know the specs are intended to have clients<-->server as 'one to one' so I was wondering whether my use case is viable / planned...

**Comment by jspahrsummers** [comment]
Your server should include both the SSE endpoint and the POST message endpoint on the same origin, though. Even if requests are issued from localhost, they should always be directed to the same remote origin.

**Comment by Ejb503** [comment]
This is accurate, I suspect that I've overcomplicated things by using a fork of the MCP inspector for the client (so probably doubled up the servers)..., 

Not using the SDK for the server is the complicating factor here... 

Skill issue :) I'll figure it out, keep up the good work.

**Comment by Ejb503** [comment]
![image](https://github.com/user-attachments/assets/f314551f-d1fa-495b-b99d-6423fe9d5fc3)

Definite skill issue :)
