### ISSUE TITLE
Use of MUST / MUST NOT / SHOULD / SHOULD NOT / ...

### ISSUE THREAD

**Issue by LaurentAjdnik** [modelcontextprotocol/specification#99]
These key words are used in many places.

According to [BCP14](https://www.rfc-editor.org/bcp/bcp14.txt), it is recommended to incorporate this phrase near the beginning of any specification that uses them:

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119).

PS: Yes, I do agree to PR if needed. 😁

**Comment by jspahrsummers** [comment]
Thanks, agreed! We'd be happy to review a PR. 🙏

**Comment by LaurentAjdnik** [comment]
PR #103 sent.

Final text taken from RFC8174, which updated RFC2119:

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://datatracker.ietf.org/doc/html/bcp14) [[RFC2119](https://datatracker.ietf.org/doc/html/rfc2119)] [[RFC8174](https://datatracker.ietf.org/doc/html/rfc8174)] when, and only when, they appear in all capitals, as shown here.
